# Generated by Django 3.2 on 2021-04-23 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='contactcategory',
            options={'verbose_name_plural': 'Contact Categories'},
        ),
        migrations.AlterModelOptions(
            name='institutioncategory',
            options={'verbose_name_plural': 'Institution Categories'},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='contacts',
        ),
    ]
