# Generated by Django 3.2 on 2021-04-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_contactdetail_institution'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactdetail',
            table='contact_details',
        ),
    ]
