# Generated by Django 3.2 on 2021-04-23 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_alter_contactdetail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactcategory',
            table='contact_categories',
        ),
    ]
