# Generated by Django 3.2 on 2021-04-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_alter_institutioncategory_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='institution',
            table='institutions',
        ),
    ]
